apiVersion: v1
kind: Namespace
metadata:
  name: miespacio2
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: miespacio
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: miespacio2
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

