apiVersion: v1
kind: Pod
metadata:
  name: nginx
 # namespace: miespacio #aqui le decimos a que ns corresponde este pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
