kind: Pod
apiVersion: v1
metadata:
  name: pv-pod  # Nombre del Pod
spec:
  volumes:
    - name: pv-storage  # Nombre del volumen
      persistentVolumeClaim:
       claimName: claim001  # Nombre del PersistentVolumeClaim que se usar치 para este volumen
  containers:
    - name: pv-container  # Nombre del contenedor
      image: nginx:1.7.9  # Imagen del contenedor que se usar치
      ports:
        - containerPort: 80  # Puerto que se expone en el contenedor
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"  # Ruta del contenedor donde se montar치 el volumen
          name: pv-storage  # Nombre del volumen que se montar치 en esta ruta
