apiVersion: v1
kind: ReplicationController
metadata:
  name: mi-replication-controller
spec:
  replicas: 3
  template: # mueve esta sección dentro del campo "spec"
    metadata:
      labels:
        app: mi-aplicacion
        tier: prod
    spec:
      containers:
        - name: mi-contenedor
          image: nginx
          ports:
            - containerPort: 80
