apiVersion: v1
kind: ReplicationController
metadata:
  name: mi--segundo-replication-controller
  labels:
    project: nginx2
spec:
  replicas: 3
  selector:
    project: nginx2
  template:
    metadata:
      labels:
        app: mi-aplicacion
        tier: prod
        project: nginx2
    spec:
      containers:
        - name: mi-contenedor
          image: nginx
          ports:
            - containerPort: 80
